### ISSUE TITLE
should `Rules` run both accept and reject?

### ISSUE THREAD

**Issue by jkthorne** [watzon/arachnid#1]
I am just digging into this code but is seems to me reject should also run even if there is an accept proc
https://github.com/watzon/arachnid/blob/master/src/arachnid/rules.cr#L21.

This is just a thought but what about a method `#valid?` or `#test` and have it run the accept procs and the reject procs?

Something like
```crystal
    def test(data : T)
      result = true
      result = @accept.any? { |rule| test_data(data, rule) } unless @accept.empty?
      result = !@reject.any? { |rule| test_data(data, rule) } unless @reject.empty? || result == false
      result
    end
```

**Comment by watzon** [comment]
I've actually been struggling with that logic, but this could work. Let me do some testing and I may just implement that.

**Comment by watzon** [comment]
I went ahead and used that logic for the `#accept?` method because I like it better. Thanks :)
