### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by jkthorne** [watzon/arachnid#2]
I want to help with this repo it is something I have wanted in crystal.  But, to contribute, I would like to verify some of the code.  How are you currently testing this?

**Comment by watzon** [comment]
It's not being tested currently other than manually. If you want to help with writing tests I'd be more than happy to accept any PRs. Testing any HTTP based library is always a pain in the ass.

**Comment by jkthorne** [comment]
Very true I have a project this might work well for.  It I build a scraper I can use that for some testing.

**Comment by watzon** [comment]
Sounds good. I know there are going to be plenty of bugs so it would be nice to have a real world scenario to test it with.
