### ISSUE TITLE
"Outsourcing" the client

### ISSUE THREAD

**Issue by bararchy** [watzon/arachnid#3]
Is there any way to handle the request and response outside of the context of the crawler, and just get from it the HTTP::Request and return an HTTP::Client::Response?

**Comment by watzon** [comment]
Currently the `Agent` is too closely tied to the `SessionCache` to allow that, but it could be possible in the future. What's the use case?

**Comment by bararchy** [comment]
TBH it's a very special use case and I doubt it will matter to anyone other then my specific need, so I won't ask for a personal feature :) 
Just wanted to know if it was available "off the shelf".

Thanks for making awesome code :)
