### ISSUE TITLE
Can't compile (install) with Crystal 0.30

### ISSUE THREAD

**Issue by petr-fischer** [watzon/arachnid#4]
```
➤  shards build --release
Dependencies are satisfied
Building: arachnid
Error target arachnid failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/arachnid/session_cache.cr:67:20

 67 | headers: headers,
               ^------
Error: undefined local variable or method 'headers' for Arachnid::SessionCache
```

**Comment by jkthorne** [comment]
I am getting the same error on 0.29

**Comment by watzon** [comment]
This should be fixed soon as I migrate Arachnid to using watzon/marionette as the HTTP client. It's going to require that firefox be installed so it can use Firefox to browse, but it should make Arachnid a lot more powerful and I'll be able to fix these kinds of issues.

Should be done before monday :crossed_fingers:

**Comment by petr-fischer** [comment]
Will be there still an option to use default Crystal HTTP client, or game over without Firefox? Thanks.

**Comment by jkthorne** [comment]
I would like an option to keep it thin and simple.
Sometimes you need firefox but I like the idea of not having to allocate a render if I dont have to.

**Comment by watzon** [comment]
Yeah I'm thinking of a way to handle that right now. I think I'll be able to keep the base HTTP client working

**Comment by watzon** [comment]
This should be fixed now. Closing.
