### ISSUE TITLE
Images in tag <a href

### ISSUE THREAD

**Issue by webmastak** [watzon/arachnid#7]
How can I select images that are in the tag `<a href `? 
example: `<a href=image.jpg><img src=image-thumb.jpg></a>`
```
...
  spider.every_image do |resource|
    if resource.image?
      spawn do
...
```
**image-thumb.jpg** he selects, but **image.jpg** not.

**Comment by watzon** [comment]
`every_link` maybe? Sorry for the delayed response, I didn't see this.

**Comment by watzon** [comment]
So before closing this issue I want to add an updated answer for the newly released version of Arachnid. HTML parsing is now being done with [kostya/myhtml](https://github.com/kostya/myhtml) and finding images within links can now be done like this:

```crystal
agent.on_html do |page|
  nested_links = page.css("a img")
  nested_links.each do |tag|
    # do something with the tag
  end
end
```

CSS results are returned as an array of [`Myhtml::Node`](https://github.com/kostya/myhtml/blob/master/src/myhtml/node.cr).
